---
- hosts: all
  gather_facts: true

  vars_files:
    - default.config.yml

  pre_tasks:
    - name: Include playbook configuration.
      include_vars: "{{ item }}"
      with_fileglob:
        - "{{ playbook_dir }}/config.yml"
      tags: ['always']
    - name: Determine if host is using an M1 chip
      set_fact:
        arm_processor: "{{ true if 'arm' in ansible_facts.kernel_version.lower() else false }}"
    - name: Print all available facts
      ansible.builtin.debug:
        var: arm_processor
    - name: Install Rosetta 2 emulator if using an M1 chip
      ansible.builtin.script: "{{ playbook_dir }}/files/install_rosetta_on_apple_silicon.sh"
      register: rosetta_install_script_output
      when: arm_processor
    - name: Show output of previous command
      ansible.builtin.debug:
        var: rosetta_install_script_output

  roles:
    # Perform installations
    - role: tochukwuvictor.asdf
      tags: ['asdf']
      when: enable.install_from_asdf
    - role: geerlingguy.homebrew
      tags: ['brew', 'homebrew']
      when: enable.install_from_homebrew
    - role: geerlingguy.mas
      when: enable.install_from_mac_app_store
      tags: ['mas']
    - role: tochukwuvictor.terminal
      tags: ['terminal', 'tty']
      when: enable.configure_terminal

    # Restore from archive
    - role: tochukwuvictor.filesystem-archive
      tags: ['fs-archive']
      when: enable.restore_from_archive

  tasks:
    - include_tasks: tasks/ansible-setup.yml

    - import_tasks: tasks/distribute-home-config-files.yml
      when: enable.home_config_file_distribution
      tags: ['distribute-configs']

  #   - include_tasks: tasks/editor.yml
  #     when: configure_editor
  #     tags: ['editor']

  #   - include_tasks: tasks/osx.yml
  #     when: configure_osx
  #     tags: ['osx']

    - import_tasks: tasks/extra-packages.yml
      tags: ['extra-packages']
