---
- name: Ensure config file repository destination parent exists locally
  block:
    - ansible.builtin.file:
        path: "{{ config_files.repo_dest }}"
        state: directory
    - ansible.builtin.file:
        path: "{{ config_files.repo_dest }}"
        state: absent

- name: Ensure config file repository is cloned locally
  ansible.builtin.git:
    repo: "{{ config_files.repo }}"
    dest: "{{ config_files.repo_dest }}"
    version: "{{ config_files.repo_version }}"

- name: List files
  ansible.builtin.debug:
    msg: "{{ item }}"
    verbosity: 3
  when: "'.git/' not in item.path"
  with_community.general.filetree: "{{ config_files.repo_dest }}"

- name: Create config file directories
  ansible.builtin.file:
    path: "{{ ansible_facts.user_dir }}/{{ item.path }}"
    state: directory
  with_community.general.filetree: "{{ config_files.repo_dest }}"
  when:
    - item.state == 'directory'
    -  "'.git/' not in item.path"

- name: Copy files (explicitly skip directories in order to use the 'src' attribute)
  ansible.builtin.copy:
    src: '{{ item.src }}'
    dest: "{{ ansible_facts.user_dir }}/{{ item.path }}"
    mode: '{{ item.mode }}'
  with_community.general.filetree: "{{ config_files.repo_dest }}"
  when:
    - item.state == 'file'
    -  "'.git/' not in item.path"
